### ISSUE TITLE
Font, footer, links 

### ISSUE THREAD

**Issue by callistusndemo** [callistusndemo/callistusndemo.github.io#2]
[Hugo Xmin](https://xmin.yihui.org/) design inspirations 
- [x] Change fonts to match Hugo Xmin theme. 
```css
body {
  font-family: Optima, Candara, Calibri, Arial, sans-serif;
}
code {
  font-family: "Lucida Console", Monaco, monospace;
  font-size: 85%;
}
```

<img width="950" alt="image" src="https://user-images.githubusercontent.com/29136312/114615453-b82c1180-9c73-11eb-98cc-68b085bcb0ba.png">

---
- [x] Reduce the size of the arrow in the external links. 
- [x] Change footer to: "Made from digital garden template by Maxime. Powered by Jekyll and GitHub Pages."
